# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Google-Groups
version:      0.03
version_from: Groups.pm
installdirs:  site
requires:
    Date::Parse:                   2.24
    Email::Simple:                 1.6
    WWW::Mechanize:                0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
